### ISSUE TITLE
Not working :(

### ISSUE THREAD

**Issue by munirkamal** [NateWr/clc-demo-theme#1]
I just came across this, and tested it and seems not working, looks like some js error occurring. If you could help fix this that will be great.

http://www.giphy.com/gifs/3o7aDawrjGyGf1WCDm

TIA,
Munir

**Comment by NateWr** [comment]
Did you download the release package or build it from the repository's `master` branch?

**Comment by munirkamal** [comment]
Hi @NateWr,

Thank you for the response.

Sorry, yes I was able to make it load now. However, there seem some bugs. The preview not working at all in customizer, however, the output is generated fine on the live page.

![image](https://user-images.githubusercontent.com/5817882/31431493-5c43c39a-ae8d-11e7-879f-bd11e1c0488e.png)

Live-page:
![image](https://user-images.githubusercontent.com/5817882/31431519-6d7d5bd0-ae8d-11e7-9e15-5f1f4e0866d9.png)

I've set up this on a test live demo site, so you can access with this temporary login directly to check this. 
https://clctheme.demo.site/
clctheme-admin/admin123

Thanks.

**Comment by NateWr** [comment]
It looks like the REST API endpoints are responding with a `404` error (the first couple of errors in your first screenshot). When that's the case, none of the content will be able to display in the customizer.

Are you using an up-to-date version of WordPress? Do you have any plugins that might be disabling the REST API?
